EXPLANATION = 'explanation'
FACTUALITY = 'factuality'
INFORMATION_DENSITY = 'information_density'
COMMONSENSE = 'commonsense'
TEXTUAL_DESCRIPTION = 'textual_description'

ALL_RATIONALES_LIST = [EXPLANATION, FACTUALITY, INFORMATION_DENSITY, COMMONSENSE, TEXTUAL_DESCRIPTION]

GPT_CONFIG = 'gpt4o'
